// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package landing

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func perlin(canvas templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Scrollable canvas container --><div class=\"relative w-full h-[100vh] overflow-y-scroll z-0\"><script defer src=\"/static/scripts/perlin.js\"></script><script defer src=\"/static/scripts/logic.js\"></script><canvas id=\"perlinCanvas\" class=\"sticky top-0 w-screen h-screen\"></canvas><div class=\"pointer-events-none absolute bottom-20 items-end flex flex-col inline-flex w-fit right-30 text-[var(--text_2)]/60 text-xl select-none gap-y-1\"><button class=\"pointer-events-auto flex flex-row gap-2 items-center cursor-pointer accordion\"><div class=\"w-fit px-2 font-['Jersey_10'] border-2 border-[var(--text_2)]/60\">\"THE PERLIN-SYSTEM\" </div><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"size-5 transition-transform duration-700 ease-in-out\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 4.5v15m7.5-7.5h-15\"></path></svg></button><div class=\"pointer-events-auto panel text-[var(--text_2)]/70 text-[14px] mr-7 self-end text-right font-['Libre_Baskerville'] leading-relaxed w-[25%] panel-fade\"><p>A <i>perlin noise surface</i> is passed to a probabilistic function to decide whether or not to plot each \"dust point\". It uses a threshold which is sensitive to the distance from the center. Color interpolation adds a  cosmic vibe to the scenery.</p><br><p>What you see is not drawn, but <i>sampled</i> everytime you refresh the page.</p><br></div><p class=\"pointer-events-auto text-[14px] uppercase cursor-pointer hover:underline mr-7\"><a href=\"https://github.com/Jathsin/Ithaca/blob/main/static/scripts/perlin.js\">Check the code</a></p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
